feat(model inference): add table recognition and conversion to LaTeX
opendatalab/MinerU pull request #284
Opened 2024-08-01 08:43 UTC by papayalove

# What's Changed

## New Features

- Add table content recognition, we use weights of [StructEqTable](https://github.com/UniModal4Reasoning/StructEqTable-Deploy) to convert table images to LaTex.

## Instruction

- pip install pypandoc struct-eqtable==0.1.0
- Download [StructEqTable weights](https://huggingface.co/wanderkid/PDF-Extract-Kit/tree/main/models/TabRec) and put it under 'models/' directory. 
- Edit the 'table-mode' value to turn on the table recognition function which is turned off by default.
- If you did not download any models before, refer to [how to download models](docs/how_to_download_models_zh_cn.md)。

2024-08-01 09:01 UTC, drunkpig commented on magic_pdf/dict2md/ocr_mkcontent.py
> +                                        para_text += f"\n![]({join_path(img_buket_path, span['image_path'])})  \n"
表格图片的[]内应当放入表格的标题

2024-08-01 09:14 UTC, drunkpig requested changes

2024-08-01 09:14 UTC, drunkpig commented on magic_pdf/libs/config_reader.py
> +    table_mode = config.get("table-mode")
table-mode 是个名字，实际应该要表达出来的意思是“是否使能表格识别这个功能”， 修改为如“is_table_recong_enable”这样的

2024-08-01 09:14 UTC, drunkpig commented on magic_pdf/model/doc_analyze_by_custom_model.py
> +from magic_pdf.libs.config_reader import get_local_models_dir, get_device, get_table_mode
get_table_mode  在今后可能会有更多细致的控制，建议此处考虑返回一个dict， 以后会控制XX阈值，超时时间等等，留下可扩展空间。名字可以名为get_table_recong_config

2024-08-01 09:14 UTC, drunkpig commented on magic_pdf/model/magic_model.py
> +                        span["content"] = latex
此处根据之前讨论应该key为‘latex’, 即 span['latex'] = latex。这样和pdf-extract-kit的输出保持一致。能让minerU直接处理pdf-extract-kit输出的output.json

2024-08-01 09:14 UTC, drunkpig commented on magic_pdf/model/pdf_extract_kit.py
> +                    print("------------------table recognition processing begins-----------------")
print --->logger替换

2024-08-01 09:14 UTC, drunkpig commented on magic_pdf/model/pdf_extract_kit.py
> +                    print("------------------table recognition processing begins-----------------")
多处print请检查替换

2024-08-01 09:18 UTC, papayalove commented on magic_pdf/dict2md/ocr_mkcontent.py
> +                                        para_text += f"\n![]({join_path(img_buket_path, span['image_path'])})  \n"
原本没有标题，要加上去吗

2024-08-01 09:36 UTC, drunkpig commented on magic_pdf/dict2md/ocr_mkcontent.py
> +                                        para_text += f"\n![]({join_path(img_buket_path, span['image_path'])})  \n"
要加，原本没有放标题是错误的。包括图片也是。然后表格和图片的标题不能出现在正文里。

2024-08-01 10:04 UTC, papayalove commented on magic_pdf/dict2md/ocr_mkcontent.py
> +                                        para_text += f"\n![]({join_path(img_buket_path, span['image_path'])})  \n"
表格的标题要删除？

2024-08-01 10:04 UTC, papayalove commented on magic_pdf/dict2md/ocr_mkcontent.py
> +                                        para_text += f"\n![]({join_path(img_buket_path, span['image_path'])})  \n"
> 要加，原本没有放标题是错误的。包括图片也是。然后表格和图片的标题不能出现在正文里。

![企业微信截图_17225065332781](https://github.com/user-attachments/assets/89281ca2-065a-40eb-bc9a-8487236cfa51)

2024-08-02 03:13 UTC, drunkpig approved these changes

2024-08-02 03:13 UTC, merged