feat<table model>: add tablemaster with paddleocr to detect and recognize table
opendatalab/MinerU pull request #493
Opened 2024-08-27 07:30 UTC by papayalove

## Motivation

To enhance the ability of table detection and recognition, we adopt a new table structure model——Tablemaster along with paddleocr to deal with tables. TableMaster is way faster than StructEqTable.

## Modification

We add an option for table convertion. Unlike the StructEqTable, the new table model will ouput result in html codes.

## Use cases (Optional)

Change the value of "model" in magic-pdf.json to switch to TableMaster.
```json
{
  // other config
  "models-dir": "D:/models",
  "table-config": {
        "model": "TableMaster", // Another option of this value is 'struct_eqtable'
        "is_table_recog_enable": false, // Table recognition is disabled by default, modify this value to enable it
        "max_time": 400
    }
}
```

## Checklist

**Before PR**:

- [ ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [ ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [ ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [ ] The documentation has been modified accordingly, like docstring or example tutorials.

**After PR**:

- [ ] If the modification has potential influence on downstream or other related projects, this PR should be tested with those projects.
- [ ] CLA has been signed and all committers have signed the CLA in this PR.

2024-08-27 08:48 UTC, drunkpig requested changes

2024-08-27 08:48 UTC, drunkpig commented on magic_pdf/model/pdf_extract_kit.py
> +            if self.table_model_type == STRUCT_EQTABLE:
这里可否去掉条件分支改为
```python
table_model_dir = self.configs["weights"][self.table_model_type]

```

2024-08-27 08:48 UTC, drunkpig commented on magic_pdf/model/pdf_extract_kit.py
> +                    if self.table_model_type == STRUCT_EQTABLE:
同上，去掉条件分支，代码可以少维护点

2024-08-27 09:08 UTC, papayalove commented on magic_pdf/model/pdf_extract_kit.py
> +                    if self.table_model_type == STRUCT_EQTABLE:
这里两种模型产的结果格式不一样，latex和html，还是得判断一下

2024-08-27 09:35 UTC, papayalove commented on magic_pdf/model/pdf_extract_kit.py
> +            if self.table_model_type == STRUCT_EQTABLE:
done

2024-08-28 03:09 UTC, drunkpig approved these changes

2024-08-28 03:09 UTC, merged